### ISSUE TITLE
Support to group by multiple fields

### ISSUE THREAD

**Issue by tux2nicolae** [chiky123ser/auto-increment-group#2]
I need to group by two fields instead of only one, so it would be nice if this library would support it.

Proposed usage:

```
orderSchema.plugin(autoInc, {
  field: 'number',
  groupBy: 'type client',
  digits: 3,
  startAt: 1,
  incrementBy: 1,
  unique: false,
});
```

**Comment by chiky123ser** [comment]
The groupBy field now accepts a string or an array with the desired fields
`schema.plugin(autoInc, {
        groupBy: 'department'
});`

`schema.plugin(autoInc, {
       groupBy: ['department', 'floor']
});`

**Comment by tux2nicolae** [comment]
Thank you @chiky123ser, really appreciate it!
